name: Build-Test-Analysis

on:
  pull_request:
  push:
    branches: [main, develop]

jobs:
  run:
    name: Run
    uses: IngSoft-DA2/workflows/.github/workflows/reusable-build-test.yml@self-hosted
    permissions: write-all
    with:
      solution-name: 'VirtualPark.sln'
